[project]
name = "ai-analog-navigator-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi==0.119.1",
    "pydantic==2.12.3",
    "uvicorn==0.32.1",
    "whisper>=1.1.10",
]
