-- Test script for vector DB functionality
-- This script tests: INSERT → SELECT → Vector Search → Prefilter

-- Clean up any existing test data
DELETE FROM chunks WHERE source_url LIKE 'test://%';
DELETE FROM documents WHERE source_url LIKE 'test://%';

-- Insert test document
INSERT INTO documents (
  doc_id,
  source_url,
  source_type,
  title,
  lang,
  fetched_at,
  content_hash,
  status
) VALUES (
  'a0000000-0000-0000-0000-000000000001'::uuid,
  'test://example.com/page1',
  'school_hp',
  'テストドキュメント1',
  'ja',
  now(),
  'hash_test_001',
  'active'
);

-- Insert test chunks with dummy embeddings
-- Note: Using random vectors for testing. In production, these would be generated by embedding model.
INSERT INTO chunks (
  chunk_id,
  doc_id,
  chunk_index,
  text,
  token_count,
  tags,
  campus,
  department,
  source_url,
  embedding,
  embedding_model,
  embedding_dim,
  version
) VALUES 
(
  'b0000000-0000-0000-0000-000000000001'::uuid,
  'a0000000-0000-0000-0000-000000000001'::uuid,
  0,
  'これは工学部のキャンパス情報です。',
  10,
  ARRAY['engineering', 'campus'],
  'main',
  'engineering',
  'test://example.com/page1',
  array_fill(0.1, ARRAY[768])::vector,
  'text-embedding-nomic-embed-text-v1.5',
  768,
  1
),
(
  'b0000000-0000-0000-0000-000000000002'::uuid,
  'a0000000-0000-0000-0000-000000000001'::uuid,
  1,
  'これは理学部のキャンパス情報です。',
  10,
  ARRAY['science', 'campus'],
  'main',
  'science',
  'test://example.com/page1',
  array_fill(0.2, ARRAY[768])::vector,
  'text-embedding-nomic-embed-text-v1.5',
  768,
  1
),
(
  'b0000000-0000-0000-0000-000000000003'::uuid,
  'a0000000-0000-0000-0000-000000000001'::uuid,
  2,
  'これは医学部のキャンパス情報です。',
  10,
  ARRAY['medical', 'campus'],
  'hospital',
  'medical',
  'test://example.com/page1',
  array_fill(0.3, ARRAY[768])::vector,
  'text-embedding-nomic-embed-text-v1.5',
  768,
  1
);

-- ============================================================================
-- Test 1: Basic SELECT
-- ============================================================================
\echo '=== Test 1: Basic SELECT ==='
SELECT chunk_id, chunk_index, campus, department, left(text, 30) as text_preview
FROM chunks
WHERE source_url LIKE 'test://%'
ORDER BY chunk_index;

-- ============================================================================
-- Test 2: Vector similarity search (cosine distance)
-- ============================================================================
\echo ''
\echo '=== Test 2: Vector Similarity Search ==='
-- Create a query vector (similar to chunk 1's vector for testing)
WITH query_vec AS (
  SELECT array_fill(0.15, ARRAY[768])::vector as qvec
)
SELECT 
  chunk_id,
  chunk_index,
  campus,
  department,
  left(text, 30) as text_preview,
  1 - (embedding <=> query_vec.qvec) AS similarity_score
FROM chunks, query_vec
WHERE source_url LIKE 'test://%'
ORDER BY embedding <=> query_vec.qvec
LIMIT 5;

-- ============================================================================
-- Test 3: Prefilter + Vector search
-- ============================================================================
\echo ''
\echo '=== Test 3: Prefilter (campus=main) + Vector Search ==='
WITH query_vec AS (
  SELECT array_fill(0.15, ARRAY[768])::vector as qvec
)
SELECT 
  chunk_id,
  chunk_index,
  campus,
  department,
  left(text, 30) as text_preview,
  1 - (embedding <=> query_vec.qvec) AS similarity_score
FROM chunks, query_vec
WHERE source_url LIKE 'test://%'
  AND campus = 'main'  -- Prefilter
ORDER BY embedding <=> query_vec.qvec
LIMIT 5;

-- ============================================================================
-- Test 4: GIN index test (array search)
-- ============================================================================
\echo ''
\echo '=== Test 4: Array Search (tags contains engineering) ==='
SELECT 
  chunk_id,
  chunk_index,
  campus,
  department,
  tags,
  left(text, 30) as text_preview
FROM chunks
WHERE source_url LIKE 'test://%'
  AND tags @> ARRAY['engineering'];

-- ============================================================================
-- Test 5: Foreign key cascade delete
-- ============================================================================
\echo ''
\echo '=== Test 5: Cascade Delete Test ==='
\echo 'Before delete: chunks count'
SELECT COUNT(*) as chunks_count FROM chunks WHERE source_url LIKE 'test://%';

\echo 'Deleting document...'
DELETE FROM documents WHERE source_url = 'test://example.com/page1';

\echo 'After delete: chunks count (should be 0)'
SELECT COUNT(*) as chunks_count FROM chunks WHERE source_url LIKE 'test://%';

\echo ''
\echo '=== All tests completed ==='

